#!/bin/bash
export DISPLAY=:0

# Disable screen blanking
xset s off
xset -dpms
xset s noblank

# Hide mouse
setxkbmap -option terminate:ctrl_alt_bksp
unclutter &

# Wait a few seconds to ensure X is ready
sleep 5

# suppress wanings
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences

# Launch Chromium in kiosk mode
chromium --use-gl-egl --enable-reatures=VaapiVideoDecoder --hide-scrollbars --noerrdialogs --no-memcheck --kiosk http://localhost:4000/viewer --incognito --disable-translate --no-first-run &
